# Generated by Django 3.1.6 on 2021-02-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=255)),
                ('video_title', models.TextField()),
                ('description', models.TextField()),
                ('published_datetime', models.DateTimeField()),
                ('thumbnail', models.CharField(max_length=4000)),
                ('duration', models.IntegerField()),
                ('filtered_title', models.CharField(max_length=10000)),
                ('url', models.CharField(max_length=4000)),
            ],
        ),
    ]
